/* Deserif: hides AI-labeled images on facebook.com.
 *
 * Meta tags posts and comments that were made with AI with a small "AI info"
 * label (self-disclosed by the poster, or detected from C2PA / IPTC metadata).
 * This script looks for that label and swaps every content image inside the
 * labeled post or comment for a grey "AI SLOP" card: the image's pixels become
 * a transparent SVG with the same intrinsic size and the card is painted as the
 * element's background, so the layout does not move and nothing is inserted
 * into Facebook's DOM. One click puts the original back. Nothing is sent
 * anywhere; there is no server and no API key.
 */
(() => {
  'use strict';
  if (window.__deserifSlop) return;
  window.__deserifSlop = true;
  if (window !== window.top) return;

  const ATTR = 'data-deserif-slop';      // on images: blocked | shown
  const UNIT_ATTR = 'data-deserif-ai';   // on posts and comments Facebook labeled
  const MIN_SIDE = 100;                  // px; anything smaller is an avatar, emoji or icon
  const FBCDN = /^https?:\/\/[^/]*\.fbcdn\.net\//i;
  const STATIC = /\/(?:emoji\.php|rsrc\.php)\//i;
  // A "unit" is the thing a label applies to: a feed post, a comment (Facebook
  // gives both role="article"), or the photo viewer dialog.
  const LOOSE_ATTR = 'data-deserif-unit';   // containers we picked ourselves (no landmark around the label)
  const UNIT = '[role="article"],[role="dialog"],[aria-posinset],[data-pagelet^="FeedUnit"],[role="feed"] > div,[' + LOOSE_ATTR + ']';
  const BOOST = ':not(#_):not(#_):not(#_)';
  const BLANK_PREFIX = 'data:image/svg+xml';
  const DEFAULTS = { enabled: true, disabledHosts: [], slopEnabled: true };

  // Meta's label text, in the languages we know Facebook ships it in. Matched
  // against whole text nodes and aria-labels, never against sentences.
  const LABELS = new Set([
    'ai info', 'ai-info', 'made with ai', 'made by ai', 'ai generated', 'ai-generated',
    'ai generated content', 'ai-generated content', 'ai generated image', 'ai-generated image',
    'generated with ai', 'generated by ai', 'created with ai', 'edited with ai',
    'this content was generated with ai', 'this content was made with ai',
    'información de ia', 'info de ia', 'hecho con ia', 'creado con ia', 'generado con ia',
    'ki-info', 'mit ki erstellt', 'mit ki generiert',
    "infos sur l'ia", "info sur l'ia", "créé avec l'ia", "généré par l'ia", "généré avec l'ia",
    'informações sobre ia', 'feito com ia', 'criado com ia', 'gerado com ia',
    "info sull'ia", "creato con l'ia", "generato con l'ia",
    'gemaakt met ai', 'gegenereerd met ai',
    'imagined with ai', 'imagined with meta ai', 'made with meta ai', 'created with meta ai',
    'generated with meta ai', 'generated by meta ai', 'made using ai', 'created using ai', 'generated using ai',
    'this is ai content', 'ai content', 'ai label', 'labeled as ai', 'ai generated media', 'ai-generated media',
    'contains ai-generated content', 'contains ai generated content', 'this image was generated with ai',
    'this image was created with ai', 'this content was created with ai', 'this content was made using ai'
  ]);

  // The card: grey box, red prohibition sign, "AI SLOP". Painted as a CSS
  // background on the blocked <img> and scaled by the element's height.
  const CARD = [
    "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 200 160'>",
    "<circle cx='100' cy='56' r='38' fill='none' stroke='#e10600' stroke-width='11'/>",
    "<line x1='73.1' y1='29.1' x2='126.9' y2='82.9' stroke='#e10600' stroke-width='11' stroke-linecap='round'/>",
    "<text x='100' y='128' text-anchor='middle' font-family='Helvetica Neue,Helvetica,Arial,sans-serif' font-size='30' font-weight='700' fill='#fff' letter-spacing='2'>AI SLOP</text>",
    "<text x='100' y='150' text-anchor='middle' font-family='Helvetica Neue,Helvetica,Arial,sans-serif' font-size='12' fill='#fff' fill-opacity='.85'>click to show</text>",
    '</svg>'
  ].join('');
  const CARD_URL = 'data:image/svg+xml;utf8,' + encodeURIComponent(CARD);
  const TITLE = 'Facebook labels this as made with AI. Hidden by Deserif. Click to show it.';

  let settings = Object.assign({}, DEFAULTS);
  let active = false;
  let sheet = null;
  let statsTimer = 0;
  let flushTimer = 0;
  const dirty = new Set();       // units to (re)check
  const state = new WeakMap();   // img -> { unit, src, srcset, sources, title, w, h, status }
  const tracked = new Set();     // imgs with state, for enumeration
  const SEL = v => `img[${ATTR}="${v}"]`;

  /* ------------------------------------------------------------------ */
  /* Helpers                                                             */
  /* ------------------------------------------------------------------ */

  function send(msg) {
    return new Promise(resolve => {
      try {
        chrome.runtime.sendMessage(msg, resp => {
          if (chrome.runtime.lastError) return resolve(null);
          resolve(resp === undefined ? null : resp);
        });
      } catch (e) { resolve(null); }
    });
  }

  // The src attribute, not currentSrc: after Facebook swaps src on a recycled
  // element, currentSrc still reports the old picture until the next stable state.
  function srcOf(img) {
    const a = img.getAttribute('src') || '';
    return /^https?:/i.test(a) ? a : (img.currentSrc || img.src || '');
  }
  function eligible(url) { return FBCDN.test(url) && !STATIC.test(url); }

  function blankSrc(w, h) {
    return BLANK_PREFIX + ';utf8,' + encodeURIComponent(`<svg xmlns='http://www.w3.org/2000/svg' width='${w}' height='${h}'/>`);
  }

  function cssText() {
    return `${SEL('blocked')}${BOOST}{background-color:#8a8a8a!important;background-image:url("${CARD_URL}")!important;` +
      'background-position:center!important;background-size:auto min(150px,62%)!important;background-repeat:no-repeat!important;' +
      'cursor:pointer!important;filter:none!important;opacity:1!important;visibility:visible!important;}';
  }

  function ensureSheet() {
    if (sheet) return;
    try {
      sheet = new CSSStyleSheet();
      sheet.replaceSync(cssText());
      document.adoptedStyleSheets = [...document.adoptedStyleSheets, sheet];
    } catch (e) {
      sheet = document.createElement('style');
      sheet.textContent = cssText();
      (document.head || document.documentElement).appendChild(sheet);
    }
  }

  /* ------------------------------------------------------------------ */
  /* Facebook's label                                                    */
  /* ------------------------------------------------------------------ */

  function norm(t) {
    return t.replace(/[’‘`´]/g, "'").replace(/\s+/g, ' ').trim().toLowerCase()
      .replace(/^[^a-zà-ɏ]+/, '')    // sparkle icon, bullets, "· "
      .replace(/[^a-zà-ɏ]+$/, '');   // trailing "·", ".", ":" and the like
  }
  function isLabelText(t) {
    if (!t || t.length > 80) return false;
    const n = norm(t);
    if (!n) return false;
    if (LABELS.has(n)) return true;
    // "AI info · 3h", "AI info: learn more": the label followed by a separator
    const m = /^(.*?)\s*[·•|:]\s/.exec(n + ' ');
    return !!(m && LABELS.has(m[1].trim()));
  }

  // Does this unit carry Meta's label? Nested units (comments under a post)
  // are skipped: their label is theirs, not the post's.
  function hasLabel(unit) {
    const walker = document.createTreeWalker(unit, NodeFilter.SHOW_ELEMENT | NodeFilter.SHOW_TEXT, {
      acceptNode(n) {
        if (n.nodeType === 3) return isLabelText(n.data) ? NodeFilter.FILTER_ACCEPT : NodeFilter.FILTER_SKIP;
        if (n !== unit && n.matches(UNIT)) return NodeFilter.FILTER_REJECT;
        if (n.tagName === 'SCRIPT' || n.tagName === 'STYLE') return NodeFilter.FILTER_REJECT;
        const a = n.getAttribute('aria-label') || n.getAttribute('title');
        return a && isLabelText(a) ? NodeFilter.FILTER_ACCEPT : NodeFilter.FILTER_SKIP;
      }
    });
    return !!walker.nextNode();
  }

  function unitOf(node) {
    const el = node.nodeType === 1 ? node : node.parentElement;
    return el ? el.closest(UNIT) : null;
  }

  function imagesOf(unit) {
    const out = [];
    for (const img of unit.getElementsByTagName('img')) if (img.closest(UNIT) === unit) out.push(img);
    return out;
  }

  /* ------------------------------------------------------------------ */
  /* Hiding                                                              */
  /* ------------------------------------------------------------------ */

  function sizeOf(img) {
    const r = img.getBoundingClientRect();
    let w = r.width, h = r.height;
    if (!w || !h) { w = img.naturalWidth; h = img.naturalHeight; }
    if (!w || !h) { w = +img.getAttribute('width') || 0; h = +img.getAttribute('height') || 0; }
    return [w, h];
  }

  function consider(img, unit) {
    if (state.has(img)) return;
    const url = srcOf(img);
    if (!eligible(url)) return;
    const [w, h] = sizeOf(img);
    if (!w || !h) {
      // Not laid out or loaded yet: come back when it is.
      if (!img.__deserifWait) {
        img.__deserifWait = true;
        img.addEventListener('load', () => { img.__deserifWait = false; if (active) { dirty.add(unit); schedule(); } }, { once: true });
      }
      return;
    }
    if (w < MIN_SIDE || h < MIN_SIDE) return;
    const s = { unit, status: 'new' };
    state.set(img, s);
    tracked.add(img);
    block(img, s);
  }

  function block(img, s) {
    s.src = img.getAttribute('src');
    s.srcset = img.hasAttribute('srcset') ? img.getAttribute('srcset') : null;
    s.title = img.hasAttribute('title') ? img.getAttribute('title') : null;
    s.sources = [];
    const pic = img.parentElement;
    if (pic && pic.tagName === 'PICTURE') {
      for (const src of pic.querySelectorAll('source[srcset]')) { s.sources.push([src, src.getAttribute('srcset')]); src.removeAttribute('srcset'); }
    }
    const r = img.getBoundingClientRect();
    s.w = img.naturalWidth || Math.round(r.width) || 400;
    s.h = img.naturalHeight || Math.round(r.height) || 300;
    s.status = 'blocked';
    if (s.srcset != null) img.removeAttribute('srcset');
    img.setAttribute('src', blankSrc(s.w, s.h));
    img.setAttribute('title', TITLE);
    img.setAttribute(ATTR, 'blocked');
    queueStats();
  }

  function restore(img, s) {
    if (s.srcset != null) img.setAttribute('srcset', s.srcset);
    for (const [src, val] of s.sources || []) src.setAttribute('srcset', val);
    if (s.src != null) img.setAttribute('src', s.src);
    if (s.title == null) img.removeAttribute('title'); else img.setAttribute('title', s.title);
  }

  // Drop what we know about an image without touching its src (Facebook just
  // gave it a new one, or it is leaving the page).
  function forget(img) {
    const s = state.get(img);
    if (!s) return;
    if (s.status === 'blocked') {
      if (s.title == null) img.removeAttribute('title'); else img.setAttribute('title', s.title);
    }
    img.removeAttribute(ATTR);
    state.delete(img);
    tracked.delete(img);
  }

  // The label went away, or the feature was switched off: put the picture back.
  function release(img) {
    const s = state.get(img);
    if (!s) return;
    if (s.status === 'blocked') restore(img, s);
    img.removeAttribute(ATTR);
    state.delete(img);
    tracked.delete(img);
    queueStats();
  }

  function reveal(img) {
    const s = state.get(img);
    if (!s || s.status !== 'blocked') return;
    s.status = 'shown';
    restore(img, s);
    img.setAttribute(ATTR, 'shown');
    queueStats();
  }

  function rehide(img) {
    const s = state.get(img);
    if (!s || s.status !== 'shown') return;
    block(img, s);
  }

  /* ------------------------------------------------------------------ */
  /* Scanning                                                            */
  /* ------------------------------------------------------------------ */

  // A label with no landmark around it (some surfaces render posts as bare
  // divs): take the smallest enclosing block that holds a content image, and
  // never anything as big as the feed itself.
  function fallbackUnit(el) {
    let a = el.parentElement, depth = 0;
    while (a && a !== document.body && depth < 14) {
      if (a.matches(UNIT)) return a;
      const role = a.getAttribute('role');
      if (role === 'feed' || role === 'main' || a.tagName === 'MAIN') return null;
      let count = 0;
      for (const img of a.getElementsByTagName('img')) {
        if (!eligible(srcOf(img))) continue;
        const [w, h] = sizeOf(img);
        if (w >= MIN_SIDE && h >= MIN_SIDE && ++count > 8) break;
      }
      if (count > 8) return null;
      if (count >= 1) return a;
      a = a.parentElement;
      depth++;
    }
    return null;
  }

  // Labels outside every unit, within `root`: give each one a container.
  function sweepLoose(root) {
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_ELEMENT | NodeFilter.SHOW_TEXT, {
      acceptNode(n) {
        if (n.nodeType === 3) return isLabelText(n.data) ? NodeFilter.FILTER_ACCEPT : NodeFilter.FILTER_SKIP;
        if (n !== root && n.matches(UNIT)) return NodeFilter.FILTER_REJECT;
        if (n.tagName === 'SCRIPT' || n.tagName === 'STYLE') return NodeFilter.FILTER_REJECT;
        const a = n.getAttribute('aria-label') || n.getAttribute('title');
        return a && isLabelText(a) ? NodeFilter.FILTER_ACCEPT : NodeFilter.FILTER_SKIP;
      }
    });
    const containers = [];
    let n;
    while ((n = walker.nextNode())) {
      const el = n.nodeType === 3 ? n.parentElement : n;
      if (!el || el.closest(UNIT)) continue;
      const c = fallbackUnit(el);
      if (c && !containers.includes(c)) containers.push(c);
    }
    for (const c of containers) { c.setAttribute(LOOSE_ATTR, ''); process(c); }
  }

  function process(unit) {
    if (!unit.isConnected) return;
    const labeled = hasLabel(unit);
    if (labeled) unit.setAttribute(UNIT_ATTR, ''); else if (unit.hasAttribute(UNIT_ATTR)) unit.removeAttribute(UNIT_ATTR);
    for (const img of imagesOf(unit)) {
      const s = state.get(img);
      if (labeled) {
        if (!s) consider(img, unit);
        else if (s.unit !== unit) { release(img); consider(img, unit); }
        // already handled, including images the person chose to show
      } else if (s) {
        release(img);
      }
    }
  }

  function scanAll() {
    sweepLoose(document.body || document.documentElement);
    for (const u of document.querySelectorAll(UNIT)) process(u);
    // images that were blocked inside a unit that no longer exists
    for (const img of tracked) if (!img.isConnected || !state.get(img).unit.isConnected) forget(img);
    queueStats();
  }

  function schedule() {
    if (flushTimer) return;
    flushTimer = setTimeout(() => {
      flushTimer = 0;
      if (!active) { dirty.clear(); loose.clear(); return; }
      const units = Array.from(dirty);
      const looseEls = Array.from(loose).filter(el => el.isConnected);
      dirty.clear();
      loose.clear();
      for (const u of units) process(u);
      if (looseEls.length > 40) sweepLoose(document.body);
      else for (const el of looseEls) sweepLoose(el);
      queueStats();
    }, 150);
  }

  const loose = new Set();   // mutated nodes with no unit around them
  function markDirty(node) {
    const u = unitOf(node);
    if (u) dirty.add(u);
    else {
      const el = node.nodeType === 1 ? node : node.parentElement;
      if (el && el !== document.body && el !== document.documentElement) loose.add(el);
    }
  }

  // Facebook recycles <img> elements in its virtualised feed, so a src change
  // means "different picture": drop what we knew and look at it again.
  function onSrcChange(img) {
    const s = state.get(img);
    const attr = img.getAttribute('src') || '';
    if (s) {
      if (attr.startsWith(BLANK_PREFIX)) return;   // our own write
      if (s.status === 'blocked') {
        if (img.getAttribute('srcset')) { s.srcset = img.getAttribute('srcset'); img.removeAttribute('srcset'); }
        if (attr === s.src) { img.setAttribute('src', blankSrc(s.w, s.h)); return; }   // React put the original back
      } else if (attr === s.src) {
        return;
      }
      forget(img);
    }
    markDirty(img);
    schedule();
  }

  function onMutations(records) {
    for (const r of records) {
      if (r.type === 'attributes') {
        if (r.target.tagName === 'IMG' && r.attributeName !== 'aria-label') onSrcChange(r.target);
        else markDirty(r.target);
        continue;
      }
      if (r.type === 'characterData') { markDirty(r.target); continue; }
      markDirty(r.target);
      for (const n of r.addedNodes) {
        if (n.nodeType !== 1) { if (n.nodeType === 3) markDirty(n); continue; }
        markDirty(n);
        if (n.querySelectorAll) for (const u of n.querySelectorAll(UNIT)) dirty.add(u);
      }
    }
    if (dirty.size || loose.size) schedule();
  }
  const mo = new MutationObserver(onMutations);

  // Click anywhere on a blocked image (or on whatever Facebook overlays on it)
  // shows the original instead of opening the photo viewer.
  function onClick(e) {
    if (!active) return;
    let img = null;
    const t = e.target;
    if (t && t.nodeType === 1 && t.matches(SEL('blocked'))) img = t;
    else if (typeof e.clientX === 'number') {
      const stack = document.elementsFromPoint(e.clientX, e.clientY);
      img = stack.find(el => el.nodeType === 1 && el.matches(SEL('blocked'))) || null;
    }
    if (!img) return;
    e.preventDefault();
    e.stopImmediatePropagation();
    reveal(img);
  }
  document.addEventListener('click', onClick, true);

  /* ------------------------------------------------------------------ */
  /* Stats                                                               */
  /* ------------------------------------------------------------------ */

  function stats() {
    const q = v => document.querySelectorAll(SEL(v)).length;
    return { active, units: document.querySelectorAll(`[${UNIT_ATTR}]`).length, blocked: q('blocked'), shown: q('shown') };
  }

  // A report for debugging on a real Facebook page: what the script sees,
  // which images qualify, and every short piece of text mentioning "AI".
  function describe(u) {
    if (!u) return 'none';
    let d = '<' + u.tagName.toLowerCase();
    if (u.getAttribute('role')) d += ' role=' + u.getAttribute('role');
    if (u.hasAttribute('aria-posinset')) d += ' posinset=' + u.getAttribute('aria-posinset');
    if (u.getAttribute('aria-label')) d += ' aria-label="' + u.getAttribute('aria-label').slice(0, 30) + '"';
    if (u.hasAttribute(UNIT_ATTR)) d += ' LABELED';
    return d + '>';
  }

  function diagnose() {
    const q = sel => document.querySelectorAll(sel).length;
    let version = '?';
    try { version = chrome.runtime.getManifest().version; } catch (e) { /* ignore */ }
    const lines = [];
    lines.push('Deserif ' + version + ' on ' + location.host + location.pathname.slice(0, 40));
    lines.push('active=' + active + ' enabled=' + settings.enabled + ' slopEnabled=' + settings.slopEnabled + ' disabledHosts=' + JSON.stringify(settings.disabledHosts || []));
    lines.push('units: article=' + q('[role="article"]') + ' posinset=' + q('[aria-posinset]') + ' dialog=' + q('[role="dialog"]') +
      ' feedunit=' + q('[data-pagelet^="FeedUnit"]') + ' feedchild=' + q('[role="feed"] > div') + ' picked=' + q('[' + LOOSE_ATTR + ']') + ' labeled=' + q('[' + UNIT_ATTR + ']'));
    let inUnit = 0, outUnit = 0;
    const samples = [];
    for (const img of document.images) {
      const s = state.get(img);
      const url = s ? (s.src || '') : srcOf(img);
      if (!eligible(url)) continue;
      const [w, h] = sizeOf(img);
      if (w < MIN_SIDE || h < MIN_SIDE) continue;
      const u = img.closest(UNIT);
      if (u) inUnit++; else outUnit++;
      if (samples.length < 4) {
        let host = '?';
        try { host = new URL(url).host; } catch (e) { /* ignore */ }
        samples.push('  img ' + Math.round(w) + 'x' + Math.round(h) + ' ' + host + ' unit=' + describe(u) + ' state=' + (img.getAttribute(ATTR) || '-'));
      }
    }
    lines.push('fbcdn images >=' + MIN_SIDE + 'px: inUnit=' + inUnit + ' outsideUnit=' + outUnit + ' hidden=' + q(SEL('blocked')) + ' shown=' + q(SEL('shown')));
    lines.push(...samples);
    const found = [];
    const seen = new Set();
    const short = t => t && t.trim().length <= 80 && /\bai\b/i.test(t);
    const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_ELEMENT | NodeFilter.SHOW_TEXT, {
      acceptNode(n) {
        if (n.nodeType === 3) return short(n.data) ? NodeFilter.FILTER_ACCEPT : NodeFilter.FILTER_SKIP;
        if (n.tagName === 'SCRIPT' || n.tagName === 'STYLE') return NodeFilter.FILTER_REJECT;
        return short(n.getAttribute('aria-label') || n.getAttribute('title') || '') ? NodeFilter.FILTER_ACCEPT : NodeFilter.FILTER_SKIP;
      }
    });
    let n;
    while ((n = walker.nextNode()) && found.length < 12) {
      const text = n.nodeType === 3 ? n.data : (n.getAttribute('aria-label') || n.getAttribute('title'));
      const el = n.nodeType === 3 ? n.parentElement : n;
      if (!el) continue;
      const key = text.trim();
      if (seen.has(key)) continue;
      seen.add(key);
      const holder = el.parentElement || el;
      found.push('  "' + key.slice(0, 60) + '" match=' + isLabelText(text) + ' <' + el.tagName.toLowerCase() +
        (el.getAttribute('role') ? ' role=' + el.getAttribute('role') : '') + '> unit=' + describe(el.closest(UNIT)) +
        ' html=' + holder.outerHTML.replace(/\s+/g, ' ').slice(0, 240));
    }
    lines.push('short text mentioning AI (' + found.length + '):');
    lines.push(...(found.length ? found : ['  none']));
    return lines.join('\n');
  }

  function queueStats() {
    if (statsTimer) return;
    statsTimer = setTimeout(() => {
      statsTimer = 0;
      for (const img of tracked) if (!img.isConnected) { state.delete(img); tracked.delete(img); }
      send({ type: 'slop:stats', blocked: document.querySelectorAll(SEL('blocked')).length });
    }, 250);
  }

  /* ------------------------------------------------------------------ */
  /* Lifecycle                                                           */
  /* ------------------------------------------------------------------ */

  function start() {
    if (active) return;
    active = true;
    ensureSheet();
    mo.observe(document.documentElement, {
      childList: true, subtree: true, characterData: true,
      attributes: true, attributeFilter: ['src', 'srcset', 'aria-label']
    });
    scanAll();
  }

  function stop() {
    if (!active) return;
    active = false;
    mo.disconnect();
    dirty.clear();
    for (const img of Array.from(tracked)) release(img);
    for (const u of document.querySelectorAll(`[${UNIT_ATTR}]`)) u.removeAttribute(UNIT_ATTR);
    for (const u of document.querySelectorAll(`[${LOOSE_ATTR}]`)) u.removeAttribute(LOOSE_ATTR);
    loose.clear();
    queueStats();
  }

  function shouldRun() {
    return !!(settings.enabled && settings.slopEnabled && !(settings.disabledHosts || []).includes(location.hostname));
  }

  function apply(next) {
    settings = Object.assign({}, DEFAULTS, next);
    if (shouldRun()) start(); else stop();
  }

  function load() {
    return new Promise(resolve => {
      try { chrome.storage.sync.get(DEFAULTS, items => resolve(Object.assign({}, DEFAULTS, items || {}))); }
      catch (e) { resolve(Object.assign({}, DEFAULTS)); }
    });
  }

  chrome.storage.onChanged.addListener((changes, area) => {
    if (area !== 'sync') return;
    const next = Object.assign({}, settings);
    for (const k of Object.keys(changes)) next[k] = changes[k].newValue;
    apply(next);
  });

  chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
    if (!msg || typeof msg.type !== 'string' || msg.type.indexOf('slop:') !== 0) return;
    if (msg.type === 'slop:getStats') sendResponse(stats());
    else if (msg.type === 'slop:recheck') { if (active) scanAll(); sendResponse(stats()); }
    else if (msg.type === 'slop:showAll') { for (const img of document.querySelectorAll(SEL('blocked'))) reveal(img); sendResponse(stats()); }
    else if (msg.type === 'slop:hideAll') { for (const img of document.querySelectorAll(SEL('shown'))) rehide(img); sendResponse(stats()); }
    else if (msg.type === 'slop:diagnose') sendResponse(diagnose());
  });

  load().then(apply);
})();
